# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexttype',
            name='parameters',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='queryprocessortype',
            name='parameters',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searchtype',
            name='parameters',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='parameters',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
