# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('search_engine', '0002_auto_20170727_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('query_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.QueryProcessorType')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.SearchType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search_engine.SourceType')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
