# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_queryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='preprocessor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
