# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_sourcetype_preprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexttype',
            name='enable',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryprocessortype',
            name='enable',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchtype',
            name='enable',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='enable',
            field=models.NullBooleanField(default=False),
        ),
    ]
