# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_documentdata_querydata'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX query_index ON search_engine_querydata (text)',),
            ('DROP INDEX query_index on search_engine_querydata',)
        ),
    ]
