# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_auto_20171224_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrequest',
            name='free_search',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='queryrequest',
            name='time_request',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
