# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0010_queryrequest_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdata',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='documentdata',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentdata',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
